healthcheck:
  path: /healthcheck
  methods: 'GET'
  format: 'json'
  controller: App\Meet\Presentation\Http\Rest\Controller\HealthcheckController

signup:
  path: /api/v2/users
  methods: 'POST'
  format: 'json'
  controller: App\Meet\Presentation\Http\Rest\Controller\SignupController
