doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'

        profiling_collect_backtrace: '%kernel.debug%'
        types:
            extended_datetime_immutable: App\Infrastructure\Bridge\Symfony\Doctrine\types\ExtendedDateTimeImmutableType
            user_id: App\Infrastructure\Bridge\Symfony\Doctrine\types\UserIdType
            meet_id: App\Infrastructure\Bridge\Symfony\Doctrine\types\MeetIdType
            guest_id: App\Infrastructure\Bridge\Symfony\Doctrine\types\GuestIdType
            host_id: App\Infrastructure\Bridge\Symfony\Doctrine\types\HostIdType
            category: App\Infrastructure\Bridge\Symfony\Doctrine\types\CategoryType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Domain:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infrastructure/Bridge/Symfony/Doctrine/mapping/entity'
                prefix: 'App\Domain\Entity'
                alias: Domain

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            #dbname_suffix: '_test%env(default::TEST_TOKEN)%'
            connections:
                default:
                    use_savepoints: true

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
