version: '3.9'

networks:
  familymeet.com:
    name: familymeet.com

services:


#  web:
#    image: nginx:latest
#    ports:
#      - '8080:80'
#    volumes:
#      - ./public:/var/www/public
#      - ./src:/var/www/src
#      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - php-fpm

#  php-fpm:
#    build:
#      context: .
#      target: symfony_php
#    depends_on:
#      - db
#      - mailhog
#    volumes:
#      - ./public:/var/www/public
#      - ./src:/var/www/src
#      - ./tests:/var/www/tests
#      - ./vendor:/var/www/vendor
#      - ./migrations:/var/www/migrations
#      - ./var:/var/www/var
#      - ./templates:/var/www/templates
#      - ./config:/var/www/config
#      - ./bin:/var/www/bin
#      - ./.env:/var/www/.env
#      - ./.env.test:/var/www/.env.test
#      - ./phpunit.xml.dist:/var/www/phpunit.xml.dist
#      - ./composer.json:/var/www/composer.json
#      - ./composer.lock:/var/www/composer.lock
#      - ./phpstan.neon:/var/www/phpstan.neon
#      - ./phpstan-baseline.neon:/var/www/phpstan-baseline.neon

  frankenphp:
    #image: dunglas/frankenphp
    # uncomment the following line if you want to use a custom Dockerfile
    build:
      context: .
      target: runner
    # uncomment the following line if you want to run this in a production environment
    # restart: always
    ports:
      - "8080:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    environment:
      DATABASE_URL: mysql://user:password@db/familymeet?serverVersion=8.0.32&charset=utf8mb4
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public:/app/public
      - ./src:/app/src
      - ./tests:/app/tests
      - ./vendor:/app/vendor
      - ./migrations:/app/migrations
      - ./var:/app/var
      - ./templates:/app/templates
      - ./config:/app/config
      - ./bin:/app/bin
      - ./.env:/app/.env
      - ./.env.test:/app/.env.test
      - ./phpunit.xml.dist:/app/phpunit.xml.dist
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
      - ./phpstan.neon:/app/phpstan.neon
      - ./phpstan-baseline.neon:/app/phpstan-baseline.neon
    # comment the following line in production, it allows to have nice human-readable logs in dev
    tty: true
    networks:
      - familymeet.com

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: familymeet
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - familymeet.com

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - familymeet.com

  amazon_s3:
    image: adobe/s3mock:latest
    environment:
      - initialBuckets=family-meet/users
      - 'AWS_ACCESS_KEY_ID=id'
      - 'AWS_SECRET_ACCESS_KEY=key'
    ports:
      - '9090:9090'
      - '9191:9191'
    networks:
      - familymeet.com

volumes:
  db_data: {}
  caddy_data:
  caddy_config:
