version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./public:/var/www/public
      - ./src:/var/www/src
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      target: symfony_php
    depends_on:
      - db
      - mailhog
      - elasticsearch
    volumes:
      - ./public:/var/www/public
      - ./src:/var/www/src
      - ./tests:/var/www/tests
      - ./vendor:/var/www/vendor
      - ./migrations:/var/www/migrations
      - ./var:/var/www/var
      - ./templates:/var/www/templates
      - ./config:/var/www/config
      - ./bin:/var/www/bin
      - ./.env:/var/www/.env
      - ./.env.test:/var/www/.env.test
      - ./phpunit.xml.dist:/var/www/phpunit.xml.dist
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./phpstan.neon:/var/www/phpstan.neon

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: familymeet
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - '11080:8080'

  rabbitmq:
    image: rabbitmq:3.9.29-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      node.name: elasticsearch
      discovery.seed_hosts: elasticsearch
      cluster.initial_master_nodes: elasticsearch
      cluster.name: mycluster
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: -Xms256m -Xmx256m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 120
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.10.2
    depends_on:
      - elasticsearch
    ports:
      - '5601:5601'
    environment:
      - 'ELASTIC_HOSTS=["http://elasticsearch:9200"]'

volumes:
  db_data: {}
  elasticsearch_data: {}
