version: '3.9'

networks:
  familymeet.com:
    name: familymeet.com

services:
  frankenphp:
    build:
      context: .
      target: runner
    # uncomment the following line if you want to run this in a production environment
    # restart: always
    ports:
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    environment:
      DATABASE_URL: mysql://user:password@db/familymeet?serverVersion=8.0.32&charset=utf8mb4
      SERVER_NAME: api.family-meet.lan
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public:/app/public
      - ./src:/app/src
      - ./tests:/app/tests
      - ./vendor:/app/vendor
      - ./migrations:/app/migrations
      - ./var:/app/var
      - ./templates:/app/templates
      - ./config:/app/config
      - ./bin:/app/bin
      - ./.env:/app/.env
      - ./.env.test:/app/.env.test
      - ./phpunit.xml.dist:/app/phpunit.xml.dist
      - ./php-cs-fixer.dist.php:/app/php-cs-fixer.dist.php
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
      - ./phpstan.neon:/app/phpstan.neon
      - ./phpstan-baseline.neon:/app/phpstan-baseline.neon
    # comment the following line in production, it allows to have nice human-readable logs in dev
    tty: true
    networks:
      - familymeet.com

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: familymeet
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - familymeet.com

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - familymeet.com

  amazon_s3:
    image: adobe/s3mock:latest
    environment:
      - initialBuckets=family-meet/users
      - 'AWS_ACCESS_KEY_ID=id'
      - 'AWS_SECRET_ACCESS_KEY=key'
    ports:
      - '9090:9090'
      - '9191:9191'
    networks:
      - familymeet.com

volumes:
  db_data: {}
  caddy_data: {}
  caddy_config: {}
