Meet:
    resource: ../src/Infrastructure/Bridge/Symfony/Resources/routes.yaml

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_v2_login_check:
    path: /api/v2/login
