services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Service\ElasticSearch\ElasticSearchClientGeneratorInterface:
    class: App\Service\ElasticSearch\ElasticSearchLocalClientGenerator
    arguments:
      $elasticHost: '%env(ELASTICSEARCH_HOST)%'
      $elasticPort: '%env(ELASTICSEARCH_PORT)%'
